# Generated by Django 5.2 on 2025-12-06 06:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "kg"),
                            ("g", "g"),
                            ("l", "l"),
                            ("ml", "ml"),
                            ("pcs", "cái"),
                            ("box", "hộp"),
                        ],
                        default="kg",
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Mức cảnh báo tồn tối thiểu",
                        max_digits=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("IN", "Nhập kho"),
                            ("OUT", "Xuất kho"),
                            ("ADJ", "Điều chỉnh"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Số lượng thay đổi (dương cho nhập/điều chỉnh, âm cho xuất nếu muốn)",
                        max_digits=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="dashboard.ingredient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
