# Generated by Django 5.2 on 2025-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="min_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Mức cảnh báo tồn tối thiểu",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="change",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Số lượng thay đổi (dương cho nhập/điều chỉnh, âm cho xuất nếu muốn)",
                max_digits=10,
            ),
        ),
    ]
