# Generated by Django 5.2 on 2026-01-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_ingredient_min_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="min_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        # migrations.AlterField(
        #     model_name="inventorytransaction",
        #     name="change",
        #     field=models.PositiveIntegerField(default=1),
        # ),
    ]
