# Generated by Django 5.2 on 2026-01-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_ingredient_min_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="change",
            field=models.IntegerField(default=0),  # dùng IntegerField cho âm/dương
        ),
    ]

