# Generated by Django 5.2 on 2025-12-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_size"),
        ("products", "0007_alter_cakesize_extra_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "size")},
        ),
    ]
