# Generated by Django 5.2 on 2025-11-08 18:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Người đặt"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=50, verbose_name="Số điện thoại"),
                ),
                (
                    "sender_address",
                    models.TextField(blank=True, verbose_name="Địa chỉ người gửi"),
                ),
                (
                    "recipient_address",
                    models.TextField(verbose_name="Địa chỉ người nhận"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cod", "COD"),
                            ("vnpay", "VNPay"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                        ],
                        default="cod",
                        max_length=50,
                        verbose_name="Phương thức thanh toán",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tạo"
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(default=False, verbose_name="Đã thanh toán"),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=50, verbose_name="Trạng thái"
                    ),
                ),
                (
                    "invoice_token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "paypal_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_details", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Product ID"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Tên sản phẩm"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Đơn giá"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Số lượng"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Thành tiền"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mặt hàng đơn hàng",
                "verbose_name_plural": "Mặt hàng đơn hàng",
            },
        ),
    ]
