# Generated by Django 5.2 on 2025-12-29 16:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=12,
                verbose_name="Tổng tiền",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="Đơn giá"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="Thành tiền"
            ),
        ),
    ]
