# Generated by Django 5.2 on 2026-01-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_order_total_amount_alter_orderitem_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="sender_address",
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_address",
            field=models.CharField(max_length=500, verbose_name="Địa chỉ người nhận"),
        ),
    ]
