# Generated by Django 5.2 on 2026-01-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_order_sender_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Đang xử lý"),
                    ("processing", "Đang chuẩn bị"),
                    ("shipping", "Đang vận chuyển"),
                    ("delivered", "Đã giao hàng"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
    ]
