# Generated by Django 5.2 on 2026-01-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "COD"),
                    ("vnpay", "VNPay"),
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("momo", "MoMo"),
                ],
                default="cod",
                max_length=50,
                verbose_name="Phương thức thanh toán",
            ),
        ),
    ]
