# Generated by Django 5.2 on 2026-01-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="momo_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
