# Generated by Django 5.2 on 2025-10-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("new", "Bánh mới"),
                    ("top", "Bánh bán chạy"),
                    ("sale", "Bánh khuyến mãi"),
                ],
                default="new",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
