# Generated by Django 5.2 on 2025-12-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierrequest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Mở"),
                    ("CLAIMED", "Đã nhận (đang xử lý)"),
                    ("ACCEPTED", "Đã chấp nhận"),
                    ("REJECTED", "Bị từ chối"),
                    ("CANCELLED", "Hủy"),
                    ("COMPLETED", "Hoàn thành"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
