# Generated by Django 5.2 on 2025-12-12 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_supplierrequest_completed_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierrequest",
            name="admin_decided_by",
        ),
        migrations.RemoveField(
            model_name="supplierrequest",
            name="admin_decision_at",
        ),
        migrations.RemoveField(
            model_name="supplierrequest",
            name="admin_note",
        ),
        migrations.RemoveField(
            model_name="supplierrequest",
            name="claimed_at",
        ),
        migrations.RemoveField(
            model_name="supplierrequest",
            name="claimed_by",
        ),
        migrations.RemoveField(
            model_name="supplierrequest",
            name="supplier_message",
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="supplierrequest",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="supplierrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Chờ nhà cung cấp"),
                    ("ACCEPTED", "Đã chọn nhà cung cấp"),
                    ("REJECTED", "Admin từ chối"),
                    ("COMPLETED", "Hoàn thành"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SupplierProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Đang chờ duyệt"),
                            ("APPROVED", "Được chấp nhận"),
                            ("REJECTED", "Bị từ chối"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="suppliers.supplierrequest",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="suppliers.supplierprofile",
                    ),
                ),
            ],
        ),
    ]
