# Generated by Django 5.2 on 2025-12-13 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("suppliers", "0004_inventoryitem_remove_supplierproposal_request_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderrequest",
            old_name="description",
            new_name="note",
        ),
        migrations.RemoveField(
            model_name="orderrequest",
            name="budget",
        ),
        migrations.AddField(
            model_name="orderrequest",
            name="ingredient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_requests",
                to="dashboard.ingredient",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orderrequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="orderrequest",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_SUPPLIER", "Chờ nhà cung cấp"),
                    ("WAITING_FOR_DELIVERY", "Chờ giao hàng"),
                    ("IN_DELIVERY", "Đang giao"),
                    ("COMPLETED", "Hoàn tất"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="orderrequest",
            name="unit",
            field=models.CharField(max_length=20),
        ),
    ]
