# Generated by Django 5.2 on 2025-12-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0005_rename_description_orderrequest_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Đang mở – chờ nhà cung cấp báo giá"),
                    ("SELECTED", "Đã chọn nhà cung cấp"),
                    ("IN_DELIVERY", "Đang giao hàng"),
                    ("COMPLETED", "Hoàn tất"),
                    ("CANCELLED", "Đã hủy"),
                ],
                max_length=30,
            ),
        ),
    ]
