# Generated by Django 5.2 on 2025-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0006_alter_orderrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrequest",
            name="quantity",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="supplierproposal",
            name="offered_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
