# Generated by Django 5.2 on 2025-12-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0007_alter_orderrequest_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="orderrequest",
            name="quantity",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="supplierproposal",
            name="offered_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
    ]
