# Generated by Django 5.2 on 2025-12-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0008_alter_inventoryitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="orderrequest",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="supplierproposal",
            name="offered_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
