# Generated by Django 5.2 on 2025-10-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_product_category_alter_product_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
