# Generated by Django 5.2 on 2025-12-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_materialrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="MaterialRequest",
        ),
        migrations.DeleteModel(
            name="SupplierProfile",
        ),
    ]
