"""
Django settings for first_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'first_project', 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'first_project', 'static')

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','.vercel.app']

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "http://*.ngrok-free.app",
    "https://*.vercel.app"
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'dalinlethi@gmail.com'
EMAIL_HOST_PASSWORD = 'vjyhyhixegqogltz'  # DÙNG ENV VAR trên production
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

PAYPAL_MODE = "sandbox"
PAYPAL_CLIENT_ID = "AZVepzpTTrpUTV7UM91uDHqoLJHEW6hPLdukDJG1s9RkWRWxlDDOls7bk0mulFVUhLwNAhrAzsp0-Qz0"
PAYPAL_SECRET = "EHm3a_wLzyoMTPV-porId8XVy0Y4on_C4mC-KS8Zy3nrYP85E75d4gv4miHBq8Z3jlsFWO5obH3v4BAk"
PAYPAL_API_BASE_URL = 'https://api-m.sandbox.paypal.com'
PAYPAL_CURRENCY = "USD"

# MOMO_PARTNER_CODE = "MOMOBKUN20180529"
# MOMO_ACCESS_KEY = "klmKhWeY8aMAjWo4"
# MOMO_SECRET_KEY = "at67qH6mk8w5Y1nAyMoPXG7NYgNBb9If"
# MOMO_ENDPOINT = "https://test-payment.momo.vn/v2/gateway/api/create"


VNPAY_TMN_CODE = "Q8YXZZ01"     # cấp bởi VNPay sandbox
VNPAY_HASH_SECRET = "SLDO07RP9A238MHUQOQFBH8UMTPWBICO"
VNPAY_URL = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"

SOCIAL_AUTH_FACEBOOK_KEY = '807968285620159'
SOCIAL_AUTH_FACEBOOK_SECRET = 'cc4d3e8c128db94228a22ba46591cb30'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

LOGIN_REDIRECT_URL = 'home:index'  # Trang chuyển hướng sau đăng nhập thành công
LOGOUT_REDIRECT_URL = 'home:login'  # Trang chuyển hướng sau khi đăng xuất

LOGIN_URL = '/login/'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3=)evuqad__ak($adw5+_r!9!a_#-%7%@ml04dr!-2efqo@b2!"

# SECURITY WARNING: don't run with debug turned on in production!
os.getenv('DEBUG', 'False') == 'True'




# Application definition
AUTHENTICATION_BACKENDS = [
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "home",
    "products",
    "cart",
    "payments",
    "dashboard",
    "suppliers",
    "social_django",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "first_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR/ 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart_count",
            ],
        },
    },
]

WSGI_APPLICATION = "first_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [STATIC_DIR,]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
