# Generated by Django 5.2 on 2025-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_category_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
