# Generated by Django 5.2 on 2025-12-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CakeSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("extra_price", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(blank=True, to="products.cakesize"),
        ),
    ]
