# Generated by Django 5.2 on 2025-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_cakesize_product_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cakesize",
            name="extra_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
