# Generated by Django 5.2 on 2025-12-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_cakesize_extra_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cakesize",
            name="extra_price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
